### ISSUE TITLE
Should this middleware be called at the end of the stack ?

### ISSUE THREAD

**Issue by Shenrak** [ShinGecko/neKo-Api#2] opened 2017-03-09 18:13 UTC
I have this middleware blocking my routes (can't set status, error is thrown)

``` javascript
function allowCrossDomain() {
  return function (ctx, next) {
    ctx.set('Access-Control-Allow-Origin', '*')
    ctx.set('Content-Type', 'text/html; charset=utf-8')
    ctx.set('Access-Control-Allow-Credentials', true)
    ctx.set('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')
    ctx.set('Access-Control-Allow-Headers', 'Content-Type,Authorization,Origin')
    next()
  }
}
```

Should this middleware be the last called ? Why so ?

**Comment by justinrlle** [comment] 2017-03-09 20:30
Logically, it should be used at the begin of the stack. I think the problem is that your middleware doesn't return anything when it should return a promise.

Try with the following code:
```javascript
function allowCrossDomain() {
  return function (ctx, next) {
    ctx.set('Access-Control-Allow-Origin', '*')
    ctx.set('Content-Type', 'text/html; charset=utf-8')
    ctx.set('Access-Control-Allow-Credentials', true)
    ctx.set('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')
    ctx.set('Access-Control-Allow-Headers', 'Content-Type,Authorization,Origin')
    return next() // the subtility is here! In the return!
  }
}
```

Also, I think this middleware is allowing Cross-Origin Resource Sharing? If so, there is already an official [middleware](https://github.com/koajs/cors) for this.

**Comment by justinrlle** [comment] 2017-03-09 20:34
Note that this solution is the same as marking the function `async` and you `await` on the `next()`

**Comment by Shenrak** [comment] 2017-03-09 21:24
Your solution works fine !
This package has been created for Koa and we're using Koa2 so we'll keep going with the handmade middleware

**Comment by justinrlle** [comment] 2017-03-10 10:27
In fact, by using [koa-convert](https://github.com/koajs/convert) it won't be a problem, but let's keep it simple for now and stay with our little middleware.

So I'm closing this issue for now.

**Closed as completed** 2017-03-10 10:28 UTC
Labels: bug, question

**Comment by Shenrak** [comment] 2017-03-10 22:31
Actually I finally used [koa2-cors](https://www.npmjs.com/package/koa2-cors)
